---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: kubauth-users
  namespace: kubocd
spec:
  package:
    repository: quay.io/kubosa/packages/kubauth-grant
    tag: 0.1.1-p01
  parameters:
    users:
      - login: sa
        passwordHash: "$2a$12$iw.ywr.87sGXAkK1HSIU6OIBTyVs4/at1T7I1ueLPPt9CPxOpkmbW"  # as
        commonNames:
          - Serge ALEXANDRE
        emails:
          - sa@mycompany.com
        claims:
          company: kubotal
      - login: admin
        passwordHash: "$2a$12$0.GDdlFBEGEuDI5OKayVgOfdyiHnB4YPoFmyVmB2uHOWh36tr.d8y"  # admin
        commonNames:
          - "Kubauth & cluster administrator"
      - login: john
        passwordHash: "$2a$12$DMQMTqcTXo.1CZ8EqDxOt.echfP9oAjEJNnYIsbuMHCGrN54jsYXS"  # john
        commonNames:
          - "John DOE"

      - login: jim
        passwordHash: "$2a$12$DMQMTqcTXo.1CZ8EqDxOt.echfP9oAjEJNnYIsbuMHCGrN54jsYXS"  # john
        commonNames:
          - "Jim DOE"


    groupBindings:
      - user: admin
        group: cluster-admin
      - user: admin
        group: kubauth-admin

      - user: sa
        group: minio-admin
      - user: sa
        group: kubauth-admin

    groups:
      - name: minio-admin
        claims:
          policy: consoleAdmin
        comment: Minio admin group

# For cluster bound with kubauth-kit
#
#    clusterRoleBindings:
#      - name: oidc-cluster-admin
#        clusterRole: cluster-admin
#        groups:
#          - oidc-cluster-admins
#
#    roleBindings:
#      - name: oidc-kubauth-admin-userdb
#        role: kubauth-server-main-userdb-admin
#        namespace: kubauth-users
#        groups:
#          - oidc-kubauth-admin
