

---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: kubocd-webhooks
  namespace: kubocd
spec:
  description: Second stage of kubocd installation
  package:
    repository: quay.io/kubocd/packages/kubocd-webhooks
    tag: v0.2.1-p01
    interval: 30m
  parameters:
    replicaCount: 1
