---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kubocd-controller
  namespace: flux-system
spec:
  interval: 1m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://quay.io/kubocd/charts/kubocd-ctrl
  ref:
    semver: "= v0.2.2"


---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubocd-controller
  namespace: flux-system
spec:
  interval: 1m
  serviceAccountName: kustomize-controller
  targetNamespace: kubocd
  storageNamespace: flux-system
  releaseName: kubocd-ctrl
  timeout: 5m
  install:
    createNamespace: true
    remediation:
      retries: 30
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 30
      remediateLastFailure: true
  chartRef:
    kind: OCIRepository
    name: kubocd-controller
    namespace: flux-system
  values:
    image:
      #repository: host.docker.internal:5001/kubocd/kubocd
      repository: quay.io/kubocd/kubocd
      pullPolicy: Always
    extraNamespaces:
      - name: contexts
    contexts:
      - name: cluster
        namespace: contexts
        protected: true
        description: Context specific to the cluster 'kubo3'
        context:
          cluster:
            name: kubo3
            domain: kubo3.mbp
            apiServerURL: https://127.0.0.1:5449
          ingress:
            className: nginx
            domain: ingress.kubo3.mbp
            kubernetes:
              enabled: true
          storageClass:
            data: standard
            workspace: standard
          # This is for cert-manager's users
          certificateIssuer:
            public: cluster-odp
            internal: cluster-internal
          networkPolicies: true

    config:
      packageRedirects:
#        - oldPrefix: quay.io/kubocd/packages
#          newPrefix: host.docker.internal:5001/packages
#          certSecretRef:
#            name: certs-bundle
      clusterRoles:
        - storage
      imageRedirects:
#      - oldPrefix: quay.io/kubocd/kubocd
#        newPrefix: host.docker.internal:5001/kubocd/kubocd
      defaultContexts:
        - name: cluster
          namespace: contexts
    controller:
      enabled: true
      replicaCount: 1
      logger:
        mode: dev
        level: info
      metrics:
        enabled: false
        secured: false

