---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: kubauth-users
  namespace: kubocd
spec:
  package:
    repository: quay.io/kubosa/packages/kubauth-grant
    tag: 0.1.1-p01
  parameters:

    # For cluster bound with kubauth-kit

    clusterRoleBindings:
      - name: oidc-cluster-admin
        clusterRole: cluster-admin
        groups:
          - oidc-cluster-admins
