---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: kubauth
  namespace: kubocd
spec:
  description: Oidc server
  protected: false
  package:
    repository: quay.io/kubocd/packages/kubauth
    tag: 0.1.1-p01
    interval: 30m
  targetNamespace: kubauth
  createNamespace: true
  specPatchByModule:
    main:
      values:
        oidc:
          dumpExchanges: 6
          image:
            pullPolicy: Always
            #tag: 0.1.0-snapshot-ubuntu
  parameters:
    oidc:
      logger:
        level: debug
      allowPasswordGrant: true
    data:
      userdb:
        users:
          - login: admin
            spec:
              passwordHash: "$2a$12$0.GDdlFBEGEuDI5OKayVgOfdyiHnB4YPoFmyVmB2uHOWh36tr.d8y"  # admin
              commonNames:
                - "Kubauth administrator"
          - login: john
            spec:
              passwordHash: "$2a$12$DMQMTqcTXo.1CZ8EqDxOt.echfP9oAjEJNnYIsbuMHCGrN54jsYXS"  # john
              commonNames:
                - "John DOE"
              claims:
                company: kubotal
        groupBindings:
          - user: admin
            group: kubauth-admins
          - user: admin
            group: system:masters
      oidc:
        oidcClients:
          - name: public
            spec:
              redirectURIs:
                - "http://localhost:9001/wo_callback"
                - "http://127.0.0.1:9921/callback"
                - "http://localhost:8000"
                - "http://localhost:18000"
              grantTypes: [ "implicit", "refresh_token", "authorization_code", "password", "client_credentials" ]
              responseTypes: [ "id_token", "code", "token", "id_token token", "code id_token", "code token", "code id_token token" ]
              scopes: [ "openid", "offline", "profile", "groups", "email", "offline_access", "xxx" ]
              description: A test OIDC public client
              forceOpenIdScope: false
              accessTokenLifespan: 5m
              refreshTokenLifespan: 30m
              idTokenLifespan: 5m
              public: true

          - name: k8s
            spec:
              redirectURIs:
                - "http://127.0.0.1:9921/callback"
                - "http://localhost:8000"
                - "http://localhost:18000"
              grantTypes: [ "implicit", "refresh_token", "authorization_code", "password", "client_credentials" ]
              responseTypes: [ "id_token", "code", "token", "id_token token", "code id_token", "code token", "code id_token token" ]
              scopes: [ "openid", "offline", "profile", "groups", "email", "offline_access" ]
              description: For kubernetes cluster access
              forceOpenIdScope: true
              accessTokenLifespan: 1m
              refreshTokenLifespan: 30m
              idTokenLifespan: 1m
              #hashedSecret: "$2a$12$bWPnINtuRRUB55qcVEV.vOOf7I88EHmKHiLzSAS9WKEtWQ.R29ce2"  # k8sSecret
              public: true




