---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: kubauth-users
  namespace: kubocd
spec:
  package:
    repository: quay.io/kubosa/packages/kubauth-grant
    tag: 0.1.2-p01
  parameters:
    users:
      - login: sa
        passwordHash: "$2a$12$iw.ywr.87sGXAkK1HSIU6OIBTyVs4/at1T7I1ueLPPt9CPxOpkmbW"  # as
        name: Serge ALEXANDRE
        emails:
          - sa@mycompany.com
        claims:
          company: kubotal
      - login: admin
        passwordHash: "$2a$12$0.GDdlFBEGEuDI5OKayVgOfdyiHnB4YPoFmyVmB2uHOWh36tr.d8y"  # admin
        name: "Kubauth & cluster administrator"
      - login: john
        passwordHash: "$2a$12$DMQMTqcTXo.1CZ8EqDxOt.echfP9oAjEJNnYIsbuMHCGrN54jsYXS"  # john
        name: "John DOE"


    groupBindings:
      - user: admin
        group: cluster-admins
      - user: admin
        group: kubauth-admins
      - user: admin
        group: minio-admins

      - user: sa
        group: minio-admins
      - user: sa
        group: kubauth-admins

      - user: sergea
        group: devs
      - user: sergea
        group: minio-admins

    groups:
      - name: minio-admins
        claims:
          policy: consoleAdmin
        comment: Minio admin group

    # For cluster bound with kubauth-kit

    clusterRoleBindings:
      - name: oidc-cluster-admin
        clusterRole: cluster-admin
        groups:
          - oidc-cluster-admins

    roleBindings:
      - name: oidc-kubauth-admin-ucrd
        role: kubauth-server-main-ucrd-admin
        namespace: kubauth-users
        groups:
          - oidc-kubauth-admin
