---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: releases-apps1
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 10s
  path: ./clusters/kind/m48/kubo2/releases-apps1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
      namespace: flux-system