
---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: minio2
  namespace: default
spec:
  description: S3 storage sever
  protected: false
  package:
    repository: quay.io/kubocd/packages/minio
    tag: 5.4.0-p01
    interval: 30s
  targetNamespace: minio2
  createNamespace: true
  parameters:
    rootUser: minio
    rootPassword: minio123
    storage:
      driveSize: 10G
    ingresses:
      public:
        enabled: true
      clearText:
        enabled: true
    vip:
      enabled: true
      host: "{{ .Release.metadata.name }}.{{ .Context.cluster.domain }}"
    environment:
      MINIO_IDENTITY_LDAP_SERVER_ADDR: "openldap-main.openldap.svc:636"
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN: "cn=admin,dc=odp,dc=com"
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD: "admin123"
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN: "ou=Users,dc=odp,dc=com"
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER: "(uid=%s)"
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN: "ou=Groups,dc=odp,dc=com"
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER: "(&(objectclass=posixGroup)(memberUid=%s))"
      MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY: "on"
      MINIO_IDENTITY_LDAP_SERVER_INSECURE: "off"
      MINIO_IDENTITY_LDAP_SERVER_STARTTLS: "off"
      MINIO_IDENTITY_LDAP_SRV_RECORD_NAME: ""
      MINIO_IDENTITY_LDAP_COMMENT: "in-cluster openldap server"
  dependencies:
    - openldap