

---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: podinfo
  namespace: default
spec:
  description: A first sample release of podinfo
  package:
    repository: quay.io/kubocd/packages/podinfo
    tag: 6.7.1-p01
    interval: 30m
  parameters:
    tls: true
