
---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: minio1
  namespace: kubocd
spec:
  description: S3 storage sever
  protected: false
  package:
    repository: quay.io/kubosa/packages/minio
    tag: 5.4.0-p01
    interval: 30s
  targetNamespace: minio1
  createNamespace: true
  parameters:
    rootUser: minio
    rootPassword: minio123
    storage:
      driveSize: 10G
    ingresses:
      public:
        enabled: true
      clearText:
        enabled: true
    vip:
      enabled: true
      host: "{{ .Release.metadata.name }}.{{ .Context.cluster.domain }}"
    oidc:
      enabled: false
      clientId: minio1
      clientSecret: "my-secret"
  specPatchByModule:
    main:
      values:
        minio:
          clusterIssuer: cluster-odp

#
#    environment:
#      MINIO_IDENTITY_OPENID_CONFIG_URL: "https://kubauth.ingress.kubo5.mbp/.well-known/openid-configuration"
#      MINIO_IDENTITY_OPENID_CLIENT_ID: "minio1"
#      MINIO_IDENTITY_OPENID_CLIENT_SECRET: "my-secret"
#      MINIO_IDENTITY_OPENID_CLAIM_NAME: "policy"
#      MINIO_IDENTITY_OPENID_DISPLAY_NAME: "KUBAUTH"
#      MINIO_IDENTITY_OPENID_CLAIM_USERINFO: "on"
#      MINIO_IDENTITY_OPENID_REDIRECT_URI: https://minio-console-minio1.ingress.kubo5.mbp/oauth_callback
#      #MINIO_BROWSER_REDIRECT_URL: https://minio-console-minio1.ingress.kubo5.mbp
#  specPatchByModule:
#    main:
#      values:
#        minio:
#          clusterIssuer: cluster-odp
