


image:
  #repository: ghcr.io/sergealexandre/kubocd/kubocd
  #repository: quay.io/kubocd/kubocd
  repository: host.docker.internal:5001/kubocd/kubocd
  pullPolicy: Always
extraNamespaces:
  - name: contexts
contexts:
  - name: cluster
    namespace: contexts
    protected: true
    description: Context specific to the cluster 'kubo3'
    context:
      cluster:
        name: kubo3
        domain: kubo3.mbp
      ingress:
        className: nginx
        domain: ingress.kubo3.mbp
        kubernetes:
          enabled: true
      storageClass:
        data: standard
        workspace: standard
      # This is for cert-manager's users
      certificateIssuer:
        public: cluster-odp
        internal: cluster-internal
config:
  packageRedirects:
#    - oldPrefix: quay.io/kubocd/packages
#      newPrefix: host.docker.internal:5001/packages
#      certSecretRef:
#        name: certs-bundle
  clusterRoles:
    - storage
  imageRedirects:
    - oldPrefix: quay.io/kubocd/kubocd
      newPrefix: host.docker.internal:5001/kubocd/kubocd
  defaultContexts:
    - name: cluster
      namespace: contexts
controller:
  enabled: true
  replicaCount: 1
  logger:
    mode: dev
    level: info
  metrics:
    enabled: false
    secured: false

