


image:
  #repository: ghcr.io/sergealexandre/kubocd/kubocd
  #repository: quay.io/kubocd/kubocd
  repository: host.docker.internal:5001/kubocd/kubocd
  pullPolicy: Always
webhook:
  replicaCount: 1
  logger:
    mode: dev
    level: info
  metrics:
    enabled: false
    secured: false
