


image:
  #repository: ghcr.io/sergealexandre/kubocd/kubocd
  #repository: quay.io/kubocd/kubocd
  repository: host.docker.internal:5001/kubocd/kubocd
  pullPolicy: Always
extraNamespaces:
  - name: contexts
contexts:
  - name: cluster
    namespace: contexts
    description: Context specific to the cluster 'kubo3'
    context:
      cluster:
        name: kubo3
        domain: kubo3.mbp
      ingress:
        className: nginx
        hostPostfix: ingress.kubo3.mbp
        kubernetes:
          enabled: true
      storageClass:
        data: standard
        workspace: standard
      # This is for cert-manager's users
      certificateIssuer:
        public: cluster-odp
        internal: cluster-internal
    protected: true
config:
  kuboAppRedirects:
#    - oldPrefix: quay.io/kubocd/applications
#      newPrefix: host.docker.internal:5001/applications
#      certSecretRef:
#        name: certs-bundle
  #newPrefix: ghcr.io/sergealexandre/kubocd/applications
  # Other OciRepositorySpec elements
  clusterRoles:
    - storage
  #      imageRedirects:
  #        - oldPrefix: quay.io/kubocd/
  #          newPrefix: ghcr.io/sergealexandre/kubocd/
  defaultContexts:
    - name: cluster
      namespace: contexts
controller:
  enabled: true
  replicaCount: 1
  logger:
    mode: dev
    level: debug
  metrics:
    enabled: false
    secured: false
webhook:
  enabled: false