---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kubocd-controller
  namespace: flux-system
spec:
  interval: 1m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://quay.io/kubocd/charts/kubocd
  ref:
    semver: "= v0.1.1"


---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubocd-controller
  namespace: flux-system
spec:
  interval: 1m
  serviceAccountName: kustomize-controller
  targetNamespace: kubocd
  storageNamespace: flux-system
  releaseName: kubocd-ctrl
  timeout: 5m
  install:
    createNamespace: true
    remediation:
      retries: 30
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 30
      remediateLastFailure: true
  chartRef:
    kind: OCIRepository
    name: kubocd-controller
    namespace: flux-system
  values:
    image:
      #repository: ghcr.io/sergealexandre/kubocd/kubocd
      repository: quay.io/kubocd/kubocd
      pullPolicy: Always
    extraNamespaces:
      - name: contexts
    contexts:
      - name: cluster
        namespace: contexts
        description: Context specific to the cluster 'kubo1'
        context:
          cluster:
            name: kubo1
            domain: kubo1.mbp
          ingress:
            className: nginx
            hostPostfix: ingress.kubo1.mbp
            kubernetes:
              enabled: true
          storageClass:
            data: standard
            workspace: standard
          # This is for cert-manager's users
          certificateIssuer:
            public: cluster-odp
            internal: cluster-internal
        protected: true
    config:
      kuboAppRedirects:
        - oldPrefix: quay.io/kubocd/applications
          #newPrefix: ghcr.io/sergealexandre/kubocd/applications
          newPrefix: localhost:5001/applications
        # Other OciRepositorySpec elements
      clusterRoles:
        - storage
#      imageRedirects:
#        - oldPrefix: quay.io/kubocd/
#          newPrefix: ghcr.io/sergealexandre/kubocd/
      defaultContexts:
        - name: cluster
          namespace: contexts
    controller:
      enabled: true
      replicaCount: 1
      logger:
        mode: dev
        level: debug
      metrics:
        enabled: false
        secured: false
    webhook:
      enabled: false

