---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: kubauth
  namespace: kubocd
spec:
  description: Oidc server
  protected: false
  package:
    repository: quay.io/kubosa/packages/kubauth
    tag: 0.1.2-p02
    interval: 30m
  targetNamespace: kubauth
  createNamespace: true
  specPatchByModule:
    noname:
      values:
        oidc:
          dumpExchanges: 0
          image:
            pullPolicy: Always
            #tag: 0.1.0-snapshot-ubuntu
  parameters:
#    deployInControlPlane: true
    deployInControlPlane: false
    tolerations:
      - key: node-role.kubernetes.io
        operator: "Equal"
        effect: NoSchedule
        value: services
    nodeSelector:
      node-role.kubernetes.io: "services"
    oidc:
      logger:
        level: debug
      allowPasswordGrant: true

    audit:
      enabled: true

    merger:
      enabled: true

    ucrd:
      enabled: true

    ldap:
      enabled: true

