

---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: kubocd-webhooks
  namespace: kubocd
spec:
  protected: false
  description: Second stage of kubocd installation
  package:
    repository: quay.io/kubosa/packages/kubocd-webhooks
    tag: v0.2.3-snapshot-p01
    interval: 30m
  parameters:
    replicaCount: 1
    deployInControlPlane: true
