
---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: minio
  namespace: kubocd
spec:
  description: S3 storage sever
  protected: false
  package:
    repository: quay.io/kubosa/packages/minio
    tag: 5.4.0-p02
    interval: 30s
  targetNamespace: minio
  createNamespace: true
  parameters:
    rootUser: minio
    rootPassword: minio123
    storage:
      driveSize: 10G
    ingresses:
      public:
        enabled: true
      clearText:
        enabled: true
    vip:
      enabled: true
      host: "{{ .Release.metadata.name }}.{{ .Context.cluster.domain }}"
    tolerations:
      - key: node-role.kubernetes.io
        operator: "Equal"
        effect: NoSchedule
        value: services
    nodeSelector:
      node-role.kubernetes.io: "services"
    oidc:
      enabled: true
      clientId: minio
      clientSecret: minioSecret
  specPatchByModule:
    noname:
      values:
        minio:
          clusterIssuer: cluster-odp
