

---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: tools
  namespace: kubocd
spec:
  protected: false
  package:
    repository: quay.io/kubocd/packages/tools
    tag: 0.1.0-p01
    interval: 30m
  parameters:
    reloader:
      enabled: true
    replicator:
      enabled: true
    secretGenerator:
      enabled: true
  targetNamespace: tools
  createNamespace: true
