
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: default
spec:
  interval: 5m
  url: https://metallb.github.io/metallb

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb-main
  namespace: default
spec:
  chart:
    spec:
      chart: metallb
      interval: 30m0s
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: default
      version: 0.14.9
  install:
    createNamespace: true
  interval: 30m0s
  releaseName: metallb-main
  targetNamespace: metallb
  values:
    controller:
      image:
        repository: quay.io/metallb/controller
    speaker:
      frr:
        image:
          repository: quay.io/frrouting/frr
      image:
        repository: quay.io/metallb/speaker


---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: metallb-pool
  namespace: default
spec:
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://quay.io/sergealexandre/charts/metallb-pool
  ref:
    semver: "= 0.1.0"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb-pool
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: metallb-pool
    namespace: default
  dependsOn:
    - name: metallb-main
      namespace: default
  install:
    createNamespace: true
  interval: 30m0s
  releaseName: metallb-pool
  targetNamespace: metallb
  values:
    ipRanges:
      - first: 172.18.109.6
        last: 172.18.109.9


